name: Build job

on:
  workflow_dispatch:
    inputs: {}
  #push:
  #  branches: [ master ]
  #  paths-ignore:
  #    - '.github/*'
  #    - '.github/ISSUE_TEMPLATE/**'
  #    - '*.yml'
  #    - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'
      - '*.yml'
      - 'README.md'

env:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  RYUJINX_BASE_VERSION: "1.1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "PWNED!"
